add simple user with authentication
berkovichpavel/news_portal_iTechArt pull request #1
Opened 2020-10-31 11:42 UTC by berkovichpavel

2020-11-02 07:21 UTC, dzianisim requested changes

2020-11-02 07:21 UTC, dzianisim commented on app/views/layouts/application.html.erb
> +      <span>Здравствуйте, <%= current_user.email %></span>
Use English,  please

2020-11-02 07:21 UTC, dzianisim commented on app/views/devise/unlocks/new.html.erb
> +<h2>Resend unlock instructions</h2>
Move to locales, please

2020-11-03 07:06 UTC, ddzyanis approved these changes

2020-11-03 07:47 UTC, merged